### PR TITLE
fix: Exponential job solver

### LINKED ISSUE #1410: Improve performance for reclaim/preempt scenarios with many victims
### What you would like to be added?

The current solver/scenario builder for reclaim/preempt actions works by adding victims one by one until it finds a valid scenario (or exhaust all possible victims). This can lead, in some cases, to very long scheduling cycles. We should explore ways to make this more efficient.

### Why is this needed?

Improve usability of the scheduler

### PR DESCRIPTION
**Pull request by itsomri**
## Description

This PR changes the behavior of the JobSolver: instead of incremental, pod-by-pod search for a solution, it will now attempt solving in exponential steps (1 pod, 2 pods, 4 pods etc). If it fails, it will do a binary search from the last valid scenario until it finds the maximal solvable scenario.

This significantly improves reclaim/preempt/consolidate performance for large distributed jobs with many pending pods.

## Related Issues

Fixes #1410 

## Checklist

- [x] Self-reviewed
- [x] Added/updated tests (if needed)
- [x] Updated documentation (if needed)

## Release Notes

* **Performance Improvements**
  * Improved scheduler job allocation efficiency, reducing processing time for scenario evaluations.

### CODE REVIEW

File: pkg/scheduler/actions/common/solvers/job_solver.go [hunk 1]
```diff
@@ -85,7 +83,93 @@ func (s *JobSolver) Solve(
...
+
+	for hi-lo > 1 {
+		mid := (lo + hi) / 2
+		if s.tryProbeAndDiscard(ssn, state, pendingJob, tasksToAllocate, mid) {
+			lo = mid
+		} else {
+			hi = mid
+		}
+	}
+	return lo
```
[the remark this answers is not in the document]
Comment (itsomri) [reply pkg/scheduler/actions/common/solvers/job_solver.go:134]: Theoretically it might be possible in niche cases, but future scheduling attempts will retry the failed pods. Keeping this simple for now.

File: pkg/scheduler/actions/common/solvers/job_solver.go [hunk 2]
```diff
@@ -85,7 +83,93 @@ func (s *JobSolver) Solve(
...
+) int {
+	n := len(tasksToAllocate)
+	if n == 0 {
+		return 0
+	}
+
+	lo := 0
+	var hi int
+	k := 1
+	for {
```
Comment (SiorMeir) [inline pkg/scheduler/actions/common/solvers/job_solver.go]: for without condition?
is it like `while true`? if so maybe use that

File: pkg/scheduler/actions/common/solvers/job_solver.go [hunk 3]
```diff
@@ -85,7 +83,93 @@ func (s *JobSolver) Solve(
...
+func (s *JobSolver) tryProbeAndDiscard(
+	ssn *framework.Session,
+	state *solvingState,
+	pendingJob *podgroup_info.PodGroupInfo,
+	tasksToAllocate []*pod_info.PodInfo,
+	k int,
+) bool {
+	result := s.probeAtK(ssn, state, pendingJob, tasksToAllocate, k)
+	if result == nil || !result.solved {
+		log.InfraLogger.V(5).Infof("No solution found for %d tasks out of %d tasks to allocate for %s",
```
Comment (SiorMeir) [inline pkg/scheduler/actions/common/solvers/job_solver.go:148]: maybe DEBUG instead of trace?

**Review by SiorMeir — DISMISSED** [review]

File: pkg/scheduler/actions/common/solvers/job_solver.go (hunk 2 above)
Comment (itsomri) [reply pkg/scheduler/actions/common/solvers/job_solver.go]: No `while` loops in go - `for` is `while`

**Review by SiorMeir — APPROVED** [review]
